Charity/Models/IdentityModels.cs
using Microsoft.AspNet.Identity.EntityFramework;

namespace Charity.Models
{
    public class AppUser : IdentityUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    }
}

Charity/ViewModels/AccountViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Charity.ViewModels
{

    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }
    }

    public class ManageUserViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

}

Charity/Controllers/AboutController.cs
using System.Web.Mvc;

namespace Charity.Controllers
{
    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

Charity/Controllers/BlogController.cs
using System.Web.Mvc;


namespace Charity.Controllers
{
    
    
    public class BlogController : Controller
    {
        
        public ActionResult Home1()
        {
            return View();
        }
        
        public ActionResult Home2()
        {
            return View();
        }
        
        public ActionResult Post()
        {
            return View();
        }
    }
}

Charity/Controllers/ContactController.cs
using System.Web.Mvc;

namespace Charity.Controllers
{
    public class ContactController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

Charity/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Charity.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Charity/Controllers/OtherController.cs
using System.Web.Mvc;


namespace Charity.Controllers
{
    
    
    public class OtherController : Controller
    {
        
        public ActionResult FullWidth()
        {
            return View();
        }
        
        public ActionResult SideBar()
        {
            return View();
        }
        
        public ActionResult Faq()
        {
            return View();
        }
        
        public ActionResult FourOhFour()
        {
            return View();
        }
    }
}

Charity/Controllers/PortfolioController.cs
using System.Web.Mvc;


namespace Charity.Controllers
{
    
    
    public class PortfolioController : Controller
    {
        
        public ActionResult OneColumn()
        {
            return View();
        }
        
        public ActionResult TwoColumn()
        {
            return View();
        }
        
        public ActionResult ThreeColumn()
        {
            return View();
        }
        
        public ActionResult FourColumn()
        {
            return View();
        }
        
        public ActionResult SingleItem()
        {
            return View();
        }
    }
}

Charity/Controllers/ServicesController.cs
using System.Web.Mvc;

namespace Charity.Controllers
{
    public class ServicesController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

Charity/Views/Blog/Home1.cshtml
@{
    ViewBag.Title = "Blog Home 1";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Blog Home 1
                <small>Blog Homepage</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">Blog Home 1</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <h1>
                <a href="@Url.Action("Post")">A Blog Home Template for Bootstrap 3</a>
            </h1>
            <p class="lead">
                by <a href="#">Start Bootstrap</a>
            </p>
            <hr>
            <p><i class="fa fa-clock-o"></i> Posted on August 28, 2013 at 10:00 PM</p>
            <hr>
            <a href="@Url.Action("Post")">
                <img class="img-responsive" src="http://placehold.it/900x300">
            </a>
            <hr>
            <p>This is a very basic starter template for a blog homepage. It makes use of Font Awesome icons that are built into the 'Modern Business' template, and it makes use of the Bootstrap 3 pager at the bottom of the page.</p>
            <a href="@Url.Action("Post")" class="btn btn-primary">Read More <i class="fa fa-angle-right"></i></a>
            <hr>
            <h1>
                <a href="@Url.Action("Post")">Another Blog Post</a>
            </h1>
            <p class="lead">
                by <a href="#">Start Bootstrap</a>
            </p>
            <hr>
            <p><i class="fa fa-clock-o"></i> Posted on August 28, 2013 at 10:45 PM</p>
            <hr>
            <a href="@Url.Action("Post")">
                <img class="img-responsive" src="http://placehold.it/900x300">
            </a>
            <hr>
            <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science...</p>
            <a href="@Url.Action("Post")" class="btn btn-primary">Read More <i class="fa fa-angle-right"></i></a>
            <hr>
            <h1>
                <a href="@Url.Action("Post")">Third Blog Post Entry</a>
            </h1>
            <p class="lead">
                by <a href="#">Start Bootstrap</a>
            </p>
            <hr>
            <p><i class="fa fa-clock-o"></i> Posted on August 28, 2013 at 10:45 PM</p>
            <hr>
            <a href="@Url.Action("Post")">
                <img class="img-responsive" src="http://placehold.it/900x300">
            </a>
            <hr>
            <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science...</p>
            <a href="@Url.Action("Post")" class="btn btn-primary">Read More <i class="fa fa-angle-right"></i></a>
            <hr>
            <ul class="pager">
                <li class="previous">
                    <a href="#">← Older</a>
                </li>
                <li class="next">
                    <a href="#">Newer →</a>
                </li>
            </ul>
        </div>
        <div class="col-lg-4">
            <div class="well">
                <h4>Blog Search</h4>
                <div class="input-group">
                    <input type="text" class="form-control">
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-default">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!-- /input-group -->
            </div>
            <!-- /well -->
            <div class="well">
                <h4>Popular Blog Categories</h4>
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            <li>
                                <a href="#dinosaurs">Dinosaurs</a>
                            </li>
                            <li>
                                <a href="#spaceships">Spaceships</a>
                            </li>
                            <li>
                                <a href="#fried-foods">Fried Foods</a>
                            </li>
                            <li>
                                <a href="#wild-animals">Wild Animals</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            <li>
                                <a href="#alien-abductions">Alien Abductions</a>
                            </li>
                            <li>
                                <a href="#business-casual">Business Casual</a>
                            </li>
                            <li>
                                <a href="#robots">Robots</a>
                            </li>
                            <li>
                                <a href="#fireworks">Fireworks</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /well -->
            <div class="well">
                <h4>Side Widget Well</h4>
                <p>Bootstrap's default well's work great for side widgets! What is a widget anyways...?</p>
            </div>
            <!-- /well -->
        </div>
    </div>
</div>

Charity/Views/Other/FourOhFour.cshtml
@{
    ViewBag.Title = "FAQ";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                404
                <small>Page Not Found</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">404</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <p class="error-404">404</p>
            <p class="lead">The page you're looking for could not be found.</p>
            <p>Here are some helpful links to help you find what you're looking for:</p>
            <ul>
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
                <li>
                    <a href="#">Blog</a>
                </li>
                <li>
                    <a href="#">Other</a>
                </li>
            </ul>
        </div>
    </div>
</div>

Charity/Views/Portfolio/OneColumn.cshtml
@{
    ViewBag.Title = "One Column Portfolio";
}

<script>
function myFunction(imgs) {
  var expandImg = document.getElementById("expandedImg");
  var imgText = document.getElementById("imgtext");
  expandImg.src = imgs.src;
  imgText.innerHTML = imgs.alt;
  expandImg.parentElement.style.display = "block";
}
</script>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                One Column Portfolio
                <small>Showcase Your Work</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                  @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">One Column Portfolio</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-md-7">
            <a href="@Url.Action("SingleItem","Portfolio")">
                @*<img src="http://placehold.it/750x350" class="img-responsive">*@
            
                <img src="~/Images/AjazBhaiGrandFather.png" class="img-responsive"/>
            </a>
        </div>
        <div class="col-md-5">
            <h3>Farangi Family</h3>
            <h4>Grand Father of Haq Ajaz</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <a href="@Url.Action("SingleItem","Portfolio")" class="btn btn-primary">View Family Gallery <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-7">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x350" class="img-responsive">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Name</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <a href="@Url.Action("SingleItem","Portfolio")" class="btn btn-primary">View Family Detail <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-7">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x350" class="img-responsive">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Name</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <a href="@Url.Action("SingleItem","Portfolio")" class="btn btn-primary">View Family Detail <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-7">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x350" class="img-responsive">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Name</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <a href="@Url.Action("SingleItem","Portfolio")" class="btn btn-primary">View Family Detail <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-7">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x350" class="img-responsive">
            </a>
        </div>
        <div class="col-md-5">
            <h3>Project Name</h3>
            <h4>Subheading</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
            <a href="@Url.Action("SingleItem","Portfolio")" class="btn btn-primary">View Family Detail <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">«</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">»</a>
                </li>
            </ul>
        </div>
    </div>
</div>

Charity/Views/Portfolio/ThreeColumn.cshtml
@{
    ViewBag.Title = "Three Column Portfolio";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Three Column Portfolio
                <small>Showcase Your Work</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">Three Column Portfolio</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-4 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/700x400" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <hr>
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">«</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">»</a>
                </li>
            </ul>
        </div>
    </div>
</div>

Charity/Views/Portfolio/TwoColumn.cshtml
@{
    ViewBag.Title = "Two Column Portfolio";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Two Column Portfolio
                <small>Showcase Your Work</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">Two Column Portfolio</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
               @Html.ActionLink("Project Name","SingleItem","Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <hr>
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">«</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">»</a>
                </li>
            </ul>
        </div>
    </div>
</div>

Charity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Modern Business - @ViewBag.Title</title>

    <!-- Bootstrap -->
    <link href="@Url.Content("/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("/css/modern-business.css")" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>




    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

        <div class="container">

            <div class="navbar-header" style="border-bottom-width:7px;">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"> </span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
                @*@Html.ActionLink("Manchester British Pakistani 's", "Index", new { controller = "Home" }, new { @class = "navbar-brand" })*@
                <img src="~/Images/british-flag.jpg" class="navbar-brand" />
                <img src="~/Images/paksitan-flag.jpg" class="navbar-brand" />
                @Html.ActionLink("Manchester British Pakistani 's", "Index", new { controller = "Home" }, new { @class = "navbar-brand" })
            </div>


            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li id="about">
                        @Html.ActionLink("About", "Index", "About")
                    </li>
                    <li id="contact">
                        @Html.ActionLink("Ancestral", "OneColumn", "Portfolio")
                    </li>

                    <li id="contact">
                        @Html.ActionLink("Enterprenuers", "FourColumn", "Portfolio")
                    </li>
                    <li id="contact">
                        @Html.ActionLink("Bussineses", "FourColumn", "Portfolio")
                    </li>
                    <li id="contact">
                        @Html.ActionLink("Jobs", "FourColumn", "Portfolio")
                    </li>
                    <li id="services">
                        @Html.ActionLink("Charity Services", "Index", "Services")
                    </li>



                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="item" style="height:20%;">
        <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Three'); height:100%;"></div>
            </div>


    @RenderBody()

    <div class="container">

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="@Url.Content("/js/bootstrap.js")"></script>
    <script src="@Url.Content("/js/modern-business.js")"></script>
</body>
</html>